# Generated by Django 4.1.5 on 2023-01-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_rename_menu_menuitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="no_of_guests",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="inventory",
            field=models.SmallIntegerField(),
        ),
    ]
